### ISSUE TITLE
problem with cuda and pytorch version

### ISSUE THREAD

**Issue by ZhaoCinyu** [ZhiYuanZeng/fairseq-moe#2]
May I ask what are the CUDA version and exact pytorch version to run this repo? I fail to set up the environment with CUDA11.1 and pytorch1.8, always get errors like: 

ImportError: /opt/conda/lib/python3.8/site-packages/fused_layer_norm_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7optionsEv

**Comment by ZhiYuanZeng** [comment]
I have not found the import of "fused_layer_norm_cuda" in the repository. But the fairseq will use FusedLayerNorm if the apex is available, otherwise the layer norm implemented with torch will be used.
```
try:
    from apex.normalization import FusedLayerNorm as _FusedLayerNorm

    has_fused_layernorm = True

    class FusedLayerNorm(_FusedLayerNorm):
        @torch.jit.unused
        def forward(self, x):
            if not x.is_cuda:
                return super().forward(x)
            else:
                with torch.cuda.device(x.device):
                    return super().forward(x)
except ImportError:
    has_fused_layernorm = False
def LayerNorm(normalized_shape, eps=1e-5, elementwise_affine=True, export=False):
    if torch.jit.is_scripting():
        export = True
    if not export and torch.cuda.is_available() and has_fused_layernorm:
        return FusedLayerNorm(normalized_shape, eps, elementwise_affine)
    return torch.nn.LayerNorm(normalized_shape, eps, elementwise_affine)
```
Could you share more information about this error (Where is the import, Have you installed apex)?

**Comment by ZhaoCinyu** [comment]
Thanks for the response! The problem has been solved. After install apex and reinstall fairseq from the main branch, I can run the code on CUDA11 now. Sorry to bother you 😂
